
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: 'webdev'
      POSTGRES_PASSWORD: '12345'
      POSTGRES_DB: 'mydatabase'
    volumes:
    - pgdata:/var/lib/postgresql/data
    ports:
    - "5432:5432"
  backend:
    build: "./backend"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://webdev:12345@db:5432/mydatabase
    depends_on:
      - db
  
  frontend:
    build: "./frontend"
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development

volumes:
  pgdata: